// Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';

// Widgets
export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS';
export const DELETE_WIDGET_SUCCESS = 'DELETE_WIDGET_SUCCESS';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';


//panels switch
export const TOGGLE_LAYER_PANEL = 'TOGGLE_LAYER_PANEL';
export const TOGGLE_THEMATIC_MAPS = 'TOGGLE_THEMATIC_MAPS';
export const TOGGLE_COMPUTATION_PANEL = 'TOGGLE_COMPUTATION_PANEL';
export const TOGGLE_FILTER_PANEL_DIST = 'TOGGLE_FILTER_PANEL_DIST';
export const TOGGLE_FILTER_PANEL_TKO = 'TOGGLE_FILTER_PANEL_TKO';
export const TOGGLE_GRAPH_PANEL = 'TOGGLE_GRAPH_PANEL';
export const TOGGLE_LEGEND = 'TOGGLE_LEGEND';