//panels switch
export const TOGGLE_LAYER_PANEL = 'TOGGLE_LAYER_PANEL';
export const TOGGLE_THEMATIC_MAPS = 'TOGGLE_THEMATIC_MAPS';
export const TOGGLE_COMPUTATION_PANEL = 'TOGGLE_COMPUTATION_PANEL';
export const TOGGLE_FILTER_PANEL = 'TOGGLE_FILTER_PANEL';
export const TOGGLE_FILTER_PANEL_DIST_TKO = 'TOGGLE_FILTER_PANEL_DIST_TKO';
export const TOGGLE_GRAPH_PANEL = 'TOGGLE_GRAPH_PANEL';
export const TOGGLE_LEGEND = 'TOGGLE_LEGEND';
export const TOGGLE_OFF_ALL = 'TOGGLE_OFF_ALL';
export const GET_COMPUTATION_DONE = 'GET_COMPUTATION_DONE';
export const GET_COMPUTATION_FETCH = 'GET_COMPUTATION_FETCH';

//TabAnalysis
export const SELECT_ONE_SELECTED = 'SELECT_ONE_SELECTED';
export const SELECT_TWO_SELECTED = 'SELECT_TWO_SELECTED';
export const QUERY_VALUE = 'QUERY_VALUE';

//LayersPanel
export const DIST_LAYER = 'DIST_LAYER';
export const TKO_LAYER = 'TKO_LAYER';
export const SADI_LAYER = 'SADI_LAYER';
export const BOLOTA_LAYER = 'BOLOTA_LAYER';
export const MSS_LAYER = 'MSS_LAYER';
export const NAS_PUNKT_LAYER = 'NAS_PUNKT_LAYER';
export const RIVER_LAYER = 'RIVER_LAYER';
export const ROADS_LAYER = 'ROADS_LAYER';
export const TRAIN_ROAD_LAYER = 'TRAIN_ROAD_LAYER';
export const TRAIN_STATION_LAYER = 'TRAIN_STATION_LAYER';
export const TS_BUF_LAYER = 'TS_BUF_LAYER';
export const DS_BUF_STATION_LAYER = 'DS_BUF_STATION_LAYER';
export const MSS_BUF_STATION_LAYER = 'MSS_BUF_STATION_LAYER';
